version: '3'
services:
  unzipperapp:
    container_name: unzipperapp
    restart: always
    build: ../../../
    volumes:
      - ../../../data/unzipper/logs:/home/bot/app/logs
      - ../../../data/shr:/tmp/shr
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - unzippermtproto
      - unzipperbotapi
  unzippermtproto:
    container_name: unzippermtproto
    restart: always
    build: ../../../../fileutils-rest/
    env_file:
      - .env
    volumes:
      - ../../../data/unzipper/gram:/home/bot/app/gram
      - ../../../data/shr:/tmp/shr
    depends_on:
      - unzipperbotapi
  unzipperbot:
    container_name: unzipperbot
    restart: always
    build: ../../../../fileutils-bot/
    env_file:
      - .env
    volumes:
      - ../../../data/unzipper/gram:/home/bot/app/gram
    depends_on:
      - unzipperapp
  unzipperbotapi:
    container_name: unzipperbotapi
    restart: always
    build: ../../../../fileutils-bot-api/
    env_file:
      - .env
    ports:
      - 5004:5005
    volumes:
      - ../../../data/unzipper/logs:/app/logs
      - ../../../data/shr:/tmp/shr
networks:
  default:
    external:
      name: fileutils
